# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# see also: https://github.com/filipesilva/ng-github-actions/blob/master/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: php composer
      run: composer install
    - name: get geodaten
      run: wget https://tools.adfc-hamburg.de/t30-paten/daten/geodaten.sql
    - name: deploy
      run: ./deploy-on-github.sh
    - name: Run Test
      continue-on-error: true
      run: |
       cd test
       cp test/testConfig.example.json test/testConfig.json
       npm install
       npm test
    - name: Kill screen
      continue-on-error: true
      env:
       SCREENDIR: /home/runner/.screen
      run: |
       screen -X stuff ^C
       sleep 1
       screen -X quit
    - name: Show screenlog
      run: cat screenlog.*
