# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# see also: https://github.com/filipesilva/ng-github-actions/blob/master/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: php composer
      run: composer install
    - name: get geodaten
      run: wget https://tools.adfc-hamburg.de/t30-paten/daten/geodaten.sql
    - name: deploy
      run: ./deploy-on-github.sh
    - name: run php in screenlog
      env:
       SCREENDIR: /home/runner/.screen
      run: |
       screen -L -d -m /usr/bin/php -S 127.0.0.1:1234
       # every second flush log
       screen -X logfile flush 1
       sleep 2
    - name: Setup
      run: |
       curl -v -H "Content-Type: application/json" -d '{ "resetSecret": "IBs1G38VUCiH6HEIlMrqXEGXkpaq9JKy", "adminPassword": "t30adminpw", "fillInTestData": true, "registerTestUser": true}'  "http://127.0.0.1:1234/setup.php"
    - name: show log
      env:
       SCREENDIR: /home/runner/.screen
      run: |
       screen -X stuff "$(printf '%b' 'this into input\015')"
       sleep 1
       echo == Log ==
       cat screenlog.*
       echo == Log ENDE ==
    - name: import geodaten
      run: mysql -ut30paten -pt30pw t30paten < geodaten.sql
    - name: Run Test
      run: |
       cd test
       cp test/testConfig.example.json test/testConfig.json
       npm install
       npm test
    - name: Kill screen
      continue-on-error: true
      env:
       SCREENDIR: /home/runner/.screen
      run: |
       screen -X stuff ^C
       sleep 1
       screen -X quit
    - name: Show screenlog
      run: cat screenlog.*
